name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Listring & creating folder
        run: |
          ls -la
          mkdir artifact
          echo hello > artifact/world.txt
          echo "Listing artifact"
          ls -la artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-build

      - name: listing
        run: |
          ls -la

      - name: Test Docker on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT}}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/bangmimin/webapps/temonggoweb/tracking/tracking-dockerize
            ls -la
            docker ps
