name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Listring & creating folder
        run: |
          ls -la
          mkdir artifact
          echo hello > artifact/world.txt
          echo "Listing artifact"
          ls -la artifact

      - name: Upload artifact
        with:
          name: build-prod
          path: artifact
